<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-07-31T19:51:56+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1489919867,
        'latest_version' => '8.2.1',
        'do_page_reindex_check' => false,
    ],
    'cache' => [
        'blocks' => true,
        'assets' => true,
        'theme_css' => true,
        'overrides' => true,
        'pages' => 'all',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => false,
    ],
    'maintenance' => [
        'version_job_page_num' => '200',
    ],
];
