<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-08-20T08:59:11+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.canonical_ssl_url
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Trči zdravo',

        ],
    ],
];
